#!/bin/sh
#
#

# Configuration file for release/release.sh to build pc98/i386.
# Note: CHROOT_MAKEENV assumes the build host is amd64.

TARGET="pc98"
TARGET_ARCH="i386"
KERNEL="QEMU_PC98"
CHROOT_MAKEENV="TARGET=${TARGET} TARGET_ARCH=${TARGET_ARCH}"
