# Makefile.pc98 -- PC-98 kernel using the i386 compiler ABI.
# Copyright 1990 W. Jolitz
#	from: @(#)Makefile.i386	7.1 5/10/91
# $FreeBSD$
#
# Makefile for FreeBSD
#
# This makefile is constructed from a machine description:
#	config machineid
# Most changes should be made in the machine description
#	/sys/pc98/conf/``machineid''
# after which you should do
#	 config machineid
# Generic makefile changes should be made in
#	/sys/conf/Makefile.pc98
# after which config should be rerun for all machines.
#

# Which version of config(8) is required.
%VERSREQ=	600012

STD8X16FONT?=	iso

.if !defined(S)
.if exists(./@/.)
S=	./@
.else
S=	../../..
.endif
.endif

# PC-98 executes the current i386 entry ABI and therefore uses the same
# linker layout and symbols.  Keep this explicit: the machine name alone
# would otherwise select a non-existent ldscript.pc98.
LDSCRIPT_NAME?=	ldscript.${MACHINE_ARCH}

.include "$S/conf/kern.pre.mk"

INCLUDES+= -I$S/contrib/libfdt

%BEFORE_DEPEND

%OBJS

%FILES.c

%FILES.s

%FILES.m

%CLEAN

%RULES

.include "$S/conf/kern.post.mk"
